#pragma once

#include <QtWidgets/QMainWindow>
#include <QApplication>
#include <qstylefactory.h>
#include <QMainWindow>
#include <qtablewidget>
#include <qheaderview>
#include <QResizeEvent>
#include <QTimer>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QHeaderView>
#include <QApplication>
#include <QStyleFactory>
#include <QSpacerItem>
#include <QVBoxLayout>
#include <QDesktopServices>
#include <QStackedWidget>
#include <QLabel>
#include <QValidator>
#include <QBigEndianStorageType>
#include <QDebug>
#include <QToolTip>
#include <QRegularExpression>
#include <QMenu>
#include <QInputDialog>
#include <QMessageBox>
#include <QObject>
#include <QComboBox>
#include <QPlainTextEdit>
#include <QTextCharFormat>
#include <QSyntaxHighlighter>
#include <QPushButton>
#include <QFileDialog>
#include <QCheckBox>
#include <QWidget>
#include <iostream>
#include <algorithm>
#include <vector>
#include <cmath>